function dQb_dthetaDiag(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-Nov-2017 23:35:19

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel({'Crank angle [0.1*degrees]'});

% Create title
title({'dQb/dtheta Diagram'});

% Create ylabel
ylabel({'dQb/dtheta [J/degree]'});

box(axes1,'on');

% enter value--> [3100:3660],dQb_dtheta(3100:3660)*degtorad(0.1))
