function P_V(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-Nov-2017 22:53:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel({'Volume [m^3]'});

% Create title
title({'P-V diagram'});

% Create ylabel
ylabel({'Pressure [Pa]'});

box(axes1,'on');
