function sumdQb(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-Nov-2017 23:44:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create xlabel
xlabel({'Crank angle [0.1*degrees]'});

% Create title
title({'Sum(dQb/dtheta) Diagram'});

% Create ylabel
ylabel({'Sum(dQb/dtheta) [J/degree]'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2864.89182102844 3842.16454830117]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-128.800184031098 11248.5583065349]);
box(axes1,'on');
