function Tempe(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-Nov-2017 23:05:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create xlabel
xlabel({'Crank angle [0.1*degrees]'});

% Create title
title({'Temperature Diagram'});

% Create ylabel
ylabel({'Temperature [K]'});

box(axes1,'on');
